//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivstruktur.Minimum
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("dokumentbeskrivelseMinimum", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivstruktur/minimu" +
        "m/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DokumentbeskrivelseMinimum
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("systemID")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.SystemID SystemID { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("dokumenttype")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Dokumenttype Dokumenttype { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("dokumentstatus")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Dokumentstatus Dokumentstatus { get; set; }
        
        /// <summary>
        /// <para>M020</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("tittel")]
        public string Tittel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("skjerming")]
        public SkjermingMinimum Skjerming { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("gradering")]
        public GraderingMinimum Gradering { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DokumentobjektMinimum> _dokumentobjekt;
        
        [System.Xml.Serialization.XmlElementAttribute("dokumentobjekt")]
        public System.Collections.ObjectModel.Collection<DokumentobjektMinimum> Dokumentobjekt
        {
            get
            {
                return this._dokumentobjekt;
            }
            private set
            {
                this._dokumentobjekt = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DokumentobjektSpecified
        {
            get
            {
                return (this.Dokumentobjekt.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public DokumentbeskrivelseMinimum()
        {
            this._dokumentobjekt = new System.Collections.ObjectModel.Collection<DokumentobjektMinimum>();
        }
    }
}
