//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivstruktur.Minimum
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("registreringMinimum", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivstruktur/minimu" +
        "m/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JournalpostMedSaksmappeMinimum))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JournalpostMinimum))]
    public partial class RegistreringMinimum
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("systemID")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.SystemID SystemID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("skjerming")]
        public SkjermingMinimum Skjerming { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("gradering")]
        public GraderingMinimum Gradering { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DokumentbeskrivelseMinimum> _dokumentbeskrivelse;
        
        [System.Xml.Serialization.XmlElementAttribute("dokumentbeskrivelse")]
        public System.Collections.ObjectModel.Collection<DokumentbeskrivelseMinimum> Dokumentbeskrivelse
        {
            get
            {
                return this._dokumentbeskrivelse;
            }
            private set
            {
                this._dokumentbeskrivelse = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DokumentbeskrivelseSpecified
        {
            get
            {
                return (this.Dokumentbeskrivelse.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public RegistreringMinimum()
        {
            this._dokumentbeskrivelse = new System.Collections.ObjectModel.Collection<DokumentbeskrivelseMinimum>();
            this._korrespondansepart = new System.Collections.ObjectModel.Collection<KorrespondansepartMinimum>();
        }
        
        /// <summary>
        /// <para>M004</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("registreringsID")]
        public string RegistreringsID { get; set; }
        
        /// <summary>
        /// <para>M020</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("tittel")]
        public string Tittel { get; set; }
        
        /// <summary>
        /// <para>M025</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("offentligTittel")]
        public string OffentligTittel { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<KorrespondansepartMinimum> _korrespondansepart;
        
        [System.Xml.Serialization.XmlElementAttribute("korrespondansepart")]
        public System.Collections.ObjectModel.Collection<KorrespondansepartMinimum> Korrespondansepart
        {
            get
            {
                return this._korrespondansepart;
            }
            private set
            {
                this._korrespondansepart = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KorrespondansepartSpecified
        {
            get
            {
                return (this.Korrespondansepart.Count != 0);
            }
        }
    }
}
