//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivstruktur.Minimum
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("saksmappeMinimum", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivstruktur/minimu" +
        "m/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaksmappeMinimum : MappeMinimum
    {
        
        /// <summary>
        /// <para>M011</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("saksaar")]
        public int Saksaar { get; set; }
        
        /// <summary>
        /// <para>M012</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("sakssekvensnummer")]
        public int Sakssekvensnummer { get; set; }
        
        /// <summary>
        /// <para>M100</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("saksdato", DataType="date")]
        public System.DateTime Saksdato { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("administrativEnhet")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.AdministrativEnhet AdministrativEnhet { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("saksansvarlig")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Saksansvarlig Saksansvarlig { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("saksstatus")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Saksstatus Saksstatus { get; set; }
    }
}
