//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivstruktur.Minimum
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("skjermingMinimum", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivstruktur/minimu" +
        "m/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SkjermingMinimum
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("tilgangsrestriksjon")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Tilgangsrestriksjon Tilgangsrestriksjon { get; set; }
        
        /// <summary>
        /// <para>M501</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("skjermingshjemmel")]
        public string Skjermingshjemmel { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<KS.Fiks.Arkiv.Models.V1.Metadatakatalog.SkjermingMetadata> _skjermingMetadata;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("skjermingMetadata")]
        public System.Collections.ObjectModel.Collection<KS.Fiks.Arkiv.Models.V1.Metadatakatalog.SkjermingMetadata> SkjermingMetadata
        {
            get
            {
                return this._skjermingMetadata;
            }
            private set
            {
                this._skjermingMetadata = value;
            }
        }
        
        /// <summary>
        /// </summary>
        public SkjermingMinimum()
        {
            this._skjermingMetadata = new System.Collections.ObjectModel.Collection<KS.Fiks.Arkiv.Models.V1.Metadatakatalog.SkjermingMetadata>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("skjermingDokument")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.SkjermingDokument SkjermingDokument { get; set; }
        
        /// <summary>
        /// <para>M504</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("skjermingsvarighet")]
        public int SkjermingsvarighetValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SkjermingsvarighetValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M504</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Skjermingsvarighet
        {
            get
            {
                if (this.SkjermingsvarighetValueSpecified)
                {
                    return this.SkjermingsvarighetValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SkjermingsvarighetValue = value.GetValueOrDefault();
                this.SkjermingsvarighetValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M505</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("skjermingOpphoererDato", DataType="date")]
        public System.DateTime SkjermingOpphoererDatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SkjermingOpphoererDatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M505</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> SkjermingOpphoererDato
        {
            get
            {
                if (this.SkjermingOpphoererDatoValueSpecified)
                {
                    return this.SkjermingOpphoererDatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SkjermingOpphoererDatoValue = value.GetValueOrDefault();
                this.SkjermingOpphoererDatoValueSpecified = value.HasValue;
            }
        }
    }
}
