//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Metadatakatalog
{
    
    
    /// <summary>
    /// <para>M4..</para>
    /// <para>Inneholder forskjellige identifikatorer som "navn", "identifikator" (kan være fra annet system som f.eks. AD), "epostadresse" og "initialer", samt et kode element</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("identifikatorer", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/metadatakatalog/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdministrativEnhet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Saksansvarlig))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Saksbehandler))]
    public partial class Identifikatorer
    {
        
        [System.Xml.Serialization.XmlElementAttribute("navn")]
        public string Navn { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("identifikator")]
        public string Identifikator { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("initialer")]
        public string Initialer { get; set; }
        
        /// <summary>
        /// <para>M410</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("epostadresse")]
        public string Epostadresse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("kode")]
        public Kode Kode { get; set; }
    }
}
