//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Metadatakatalog
{
    
    
    /// <summary>
    /// <para>M210</para>
    /// <para>Fiks-arkiv: endret datatypen fra en systemID til en complexType som kan inneholde en eller flere identifikatorer</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("referanseTilMappe", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/metadatakatalog/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReferanseTilMappe
    {
        
        [System.Xml.Serialization.XmlElementAttribute("systemID")]
        public SystemID SystemID { get; set; }
        
        /// <summary>
        /// <para>M003</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("mappeID")]
        public string MappeID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("saksnummer")]
        public Saksnummer Saksnummer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("referanseEksternNoekkel")]
        public EksternNoekkel ReferanseEksternNoekkel { get; set; }
    }
}
