//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Metadatakatalog
{
    
    
    /// <summary>
    /// <para>M212</para>
    /// <para>Fiks-arkiv: endret datatypen fra en systemID til en complexType som kan inneholde en eller flere identifikatorer</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("referanseTilRegistrering", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/metadatakatalog/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReferanseTilRegistrering
    {
        
        [System.Xml.Serialization.XmlElementAttribute("systemID")]
        public SystemID SystemID { get; set; }
        
        /// <summary>
        /// <para>M004</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("registreringsID")]
        public string RegistreringsID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("journalnummer")]
        public Journalnummer Journalnummer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("saksJournalpostnummer")]
        public SaksJournalpostnummer SaksJournalpostnummer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("referanseEksternNoekkel")]
        public EksternNoekkel ReferanseEksternNoekkel { get; set; }
    }
}
