//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivstruktur
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("avskrivning", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivstruktur/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("avskrivning", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivstruktur/v1")]
    public partial class Avskrivning
    {
        
        /// <summary>
        /// <para>M617</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("avskrivningsdato", DataType="date")]
        public System.DateTime Avskrivningsdato { get; set; }
        
        /// <summary>
        /// <para>M618</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("avskrevetAv")]
        public string AvskrevetAv { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("avskrivningsmaate")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Avskrivningsmaate Avskrivningsmaate { get; set; }
        
        /// <summary>
        /// <para>M215</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("referanseAvskrivesAvJournalpost")]
        public string ReferanseAvskrivesAvJournalpost { get; set; }
    }
}
