//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivstruktur
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("elektroniskSignatur", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivstruktur/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElektroniskSignatur
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("elektroniskSignaturSikkerhetsnivaa")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.ElektroniskSignaturSikkerhetsnivaa ElektroniskSignaturSikkerhetsnivaa { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("elektroniskSignaturVerifisert")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.ElektroniskSignaturVerifisert ElektroniskSignaturVerifisert { get; set; }
        
        /// <summary>
        /// <para>M622</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("verifisertDato", DataType="date")]
        public System.DateTime VerifisertDato { get; set; }
        
        /// <summary>
        /// <para>M623</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("verifisertAv")]
        public string VerifisertAv { get; set; }
    }
}
