//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivstruktur
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("kryssreferanse", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivstruktur/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("kryssreferanse", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivstruktur/v1")]
    public partial class Kryssreferanse
    {
        
        /// <summary>
        /// <para>M00...</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("kryssreferanseID")]
        public string KryssreferanseID { get; set; }
        
        /// <summary>
        /// <para>M219</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("referanseTilKlasse")]
        public string ReferanseTilKlasse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("referanseTilMappe")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.ReferanseTilMappe ReferanseTilMappe { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("referanseTilRegistrering")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.ReferanseTilRegistrering ReferanseTilRegistrering { get; set; }
        
        /// <summary>
        /// <para>M2..</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("referanseTilDokumentbeskrivelse")]
        public string ReferanseTilDokumentbeskrivelse { get; set; }
    }
}
