//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivstruktur
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("moeteregistrering", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivstruktur/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Moeteregistrering : Registrering
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("moeteregistreringstype")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Moeteregistreringstype Moeteregistreringstype { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("moetesakstype")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Moetesakstype Moetesakstype { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("moeteregistreringsstatus")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Moeteregistreringsstatus Moeteregistreringsstatus { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("administrativEnhet")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.AdministrativEnhet AdministrativEnhet { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("saksbehandler")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Saksbehandler Saksbehandler { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _referanseTilMoeteregistrering;
        
        /// <summary>
        /// <para>M223</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("referanseTilMoeteregistrering")]
        public System.Collections.ObjectModel.Collection<string> ReferanseTilMoeteregistrering
        {
            get
            {
                return this._referanseTilMoeteregistrering;
            }
            private set
            {
                this._referanseTilMoeteregistrering = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferanseTilMoeteregistreringSpecified
        {
            get
            {
                return (this.ReferanseTilMoeteregistrering.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public Moeteregistrering()
        {
            this._referanseTilMoeteregistrering = new System.Collections.ObjectModel.Collection<string>();
            this._referanseFraMoeteregistrering = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _referanseFraMoeteregistrering;
        
        /// <summary>
        /// <para>M224</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("referanseFraMoeteregistrering")]
        public System.Collections.ObjectModel.Collection<string> ReferanseFraMoeteregistrering
        {
            get
            {
                return this._referanseFraMoeteregistrering;
            }
            private set
            {
                this._referanseFraMoeteregistrering = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferanseFraMoeteregistreringSpecified
        {
            get
            {
                return (this.ReferanseFraMoeteregistrering.Count != 0);
            }
        }
    }
}
