//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivstruktur
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("responstype", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivstruktur/v1")]
    public enum Responstype
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("noekler")]
        Noekler,
        
        [System.Xml.Serialization.XmlEnumAttribute("minimum")]
        Minimum,
        
        [System.Xml.Serialization.XmlEnumAttribute("utvidet")]
        Utvidet,
    }
}
