//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivstruktur
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("skjerming", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivstruktur/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("skjerming", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivstruktur/v1")]
    public partial class Skjerming
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("tilgangsrestriksjon")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Tilgangsrestriksjon Tilgangsrestriksjon { get; set; }
        
        /// <summary>
        /// <para>M501</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("skjermingshjemmel")]
        public string Skjermingshjemmel { get; set; }
        
        /// <summary>
        /// <para>M505</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("skjermingOpphoererDato", DataType="date")]
        public System.DateTime SkjermingOpphoererDatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SkjermingOpphoererDatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M505</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> SkjermingOpphoererDato
        {
            get
            {
                if (this.SkjermingOpphoererDatoValueSpecified)
                {
                    return this.SkjermingOpphoererDatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SkjermingOpphoererDatoValue = value.GetValueOrDefault();
                this.SkjermingOpphoererDatoValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("skjermingOpphoererAksjon")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Kode SkjermingOpphoererAksjon { get; set; }
    }
}
