//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("arkivnotat", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivmelding/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("arkivnotat", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivmelding/v1")]
    public partial class Arkivnotat : Registrering
    {
        
        /// <summary>
        /// <para>M103</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("dokumentetsDato", DataType="date")]
        public System.DateTime DokumentetsDatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DokumentetsDatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M103</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> DokumentetsDato
        {
            get
            {
                if (this.DokumentetsDatoValueSpecified)
                {
                    return this.DokumentetsDatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DokumentetsDatoValue = value.GetValueOrDefault();
                this.DokumentetsDatoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M104</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("mottattDato", DataType="dateTime")]
        public System.DateTime MottattDatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool MottattDatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M104</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> MottattDato
        {
            get
            {
                if (this.MottattDatoValueSpecified)
                {
                    return this.MottattDatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.MottattDatoValue = value.GetValueOrDefault();
                this.MottattDatoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M105</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("sendtDato", DataType="dateTime")]
        public System.DateTime SendtDatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SendtDatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M105</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> SendtDato
        {
            get
            {
                if (this.SendtDatoValueSpecified)
                {
                    return this.SendtDatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SendtDatoValue = value.GetValueOrDefault();
                this.SendtDatoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M109</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("forfallsdato", DataType="date")]
        public System.DateTime ForfallsdatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ForfallsdatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M109</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> Forfallsdato
        {
            get
            {
                if (this.ForfallsdatoValueSpecified)
                {
                    return this.ForfallsdatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ForfallsdatoValue = value.GetValueOrDefault();
                this.ForfallsdatoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M110</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("offentlighetsvurdertDato", DataType="date")]
        public System.DateTime OffentlighetsvurdertDatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool OffentlighetsvurdertDatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M110</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> OffentlighetsvurdertDato
        {
            get
            {
                if (this.OffentlighetsvurdertDatoValueSpecified)
                {
                    return this.OffentlighetsvurdertDatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OffentlighetsvurdertDatoValue = value.GetValueOrDefault();
                this.OffentlighetsvurdertDatoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M304</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("antallVedlegg")]
        public int AntallVedleggValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AntallVedleggValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M304</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> AntallVedlegg
        {
            get
            {
                if (this.AntallVedleggValueSpecified)
                {
                    return this.AntallVedleggValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AntallVedleggValue = value.GetValueOrDefault();
                this.AntallVedleggValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M106</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("utlaantDato", DataType="date")]
        public System.DateTime UtlaantDatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool UtlaantDatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M106</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> UtlaantDato
        {
            get
            {
                if (this.UtlaantDatoValueSpecified)
                {
                    return this.UtlaantDatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.UtlaantDatoValue = value.GetValueOrDefault();
                this.UtlaantDatoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M309</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("utlaantTil")]
        public string UtlaantTil { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Dokumentflyt> _dokumentflyt;
        
        [System.Xml.Serialization.XmlElementAttribute("dokumentflyt")]
        public System.Collections.ObjectModel.Collection<Dokumentflyt> Dokumentflyt
        {
            get
            {
                return this._dokumentflyt;
            }
            private set
            {
                this._dokumentflyt = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DokumentflytSpecified
        {
            get
            {
                return (this.Dokumentflyt.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public Arkivnotat()
        {
            this._dokumentflyt = new System.Collections.ObjectModel.Collection<Dokumentflyt>();
        }
    }
}
