//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("dokumentbeskrivelse", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivmelding/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("dokumentbeskrivelse", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivmelding/v1")]
    public partial class Dokumentbeskrivelse
    {
        
        [System.Xml.Serialization.XmlElementAttribute("systemID")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.SystemID SystemID { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("dokumenttype")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Dokumenttype Dokumenttype { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("dokumentstatus")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Dokumentstatus Dokumentstatus { get; set; }
        
        /// <summary>
        /// <para>M020</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("tittel")]
        public string Tittel { get; set; }
        
        /// <summary>
        /// <para>M021</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("beskrivelse")]
        public string Beskrivelse { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _forfatter;
        
        /// <summary>
        /// <para>M024</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("forfatter")]
        public System.Collections.ObjectModel.Collection<string> Forfatter
        {
            get
            {
                return this._forfatter;
            }
            private set
            {
                this._forfatter = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ForfatterSpecified
        {
            get
            {
                return (this.Forfatter.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public Dokumentbeskrivelse()
        {
            this._forfatter = new System.Collections.ObjectModel.Collection<string>();
            this._part = new System.Collections.ObjectModel.Collection<Part>();
            this._merknad = new System.Collections.ObjectModel.Collection<Merknad>();
            this._dokumentobjekt = new System.Collections.ObjectModel.Collection<Dokumentobjekt>();
        }
        
        /// <summary>
        /// <para>M600</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("opprettetDato", DataType="dateTime")]
        public System.DateTime OpprettetDatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool OpprettetDatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M600</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> OpprettetDato
        {
            get
            {
                if (this.OpprettetDatoValueSpecified)
                {
                    return this.OpprettetDatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OpprettetDatoValue = value.GetValueOrDefault();
                this.OpprettetDatoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M601</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("opprettetAv")]
        public string OpprettetAv { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("dokumentmedium")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Dokumentmedium Dokumentmedium { get; set; }
        
        /// <summary>
        /// <para>M301</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("oppbevaringssted")]
        public string Oppbevaringssted { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("arkivdel")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Kode Arkivdel { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("tilknyttetRegistreringSom")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.TilknyttetRegistreringSom TilknyttetRegistreringSom { get; set; }
        
        /// <summary>
        /// <para>M007</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("dokumentnummer")]
        public int DokumentnummerValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DokumentnummerValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M007</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Dokumentnummer
        {
            get
            {
                if (this.DokumentnummerValueSpecified)
                {
                    return this.DokumentnummerValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DokumentnummerValue = value.GetValueOrDefault();
                this.DokumentnummerValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M620</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("tilknyttetDato", DataType="dateTime")]
        public System.DateTime TilknyttetDatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TilknyttetDatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M620</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> TilknyttetDato
        {
            get
            {
                if (this.TilknyttetDatoValueSpecified)
                {
                    return this.TilknyttetDatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TilknyttetDatoValue = value.GetValueOrDefault();
                this.TilknyttetDatoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M621</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("tilknyttetAv")]
        public string TilknyttetAv { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Part> _part;
        
        [System.Xml.Serialization.XmlElementAttribute("part")]
        public System.Collections.ObjectModel.Collection<Part> Part
        {
            get
            {
                return this._part;
            }
            private set
            {
                this._part = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartSpecified
        {
            get
            {
                return (this.Part.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Merknad> _merknad;
        
        [System.Xml.Serialization.XmlElementAttribute("merknad")]
        public System.Collections.ObjectModel.Collection<Merknad> Merknad
        {
            get
            {
                return this._merknad;
            }
            private set
            {
                this._merknad = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MerknadSpecified
        {
            get
            {
                return (this.Merknad.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("skjerming")]
        public Skjerming Skjerming { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("gradering")]
        public Gradering Gradering { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Dokumentobjekt> _dokumentobjekt;
        
        [System.Xml.Serialization.XmlElementAttribute("dokumentobjekt")]
        public System.Collections.ObjectModel.Collection<Dokumentobjekt> Dokumentobjekt
        {
            get
            {
                return this._dokumentobjekt;
            }
            private set
            {
                this._dokumentobjekt = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DokumentobjektSpecified
        {
            get
            {
                return (this.Dokumentobjekt.Count != 0);
            }
        }
    }
}
