//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("mappe", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivmelding/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("mappe", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivmelding/v1")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Saksmappe))]
    public partial class Mappe
    {
        
        [System.Xml.Serialization.XmlElementAttribute("systemID")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.SystemID SystemID { get; set; }
        
        /// <summary>
        /// <para>M003</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("mappeID")]
        public string MappeID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("referanseForeldermappe")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.ReferanseTilMappe ReferanseForeldermappe { get; set; }
        
        /// <summary>
        /// <para>M020</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("tittel")]
        public string Tittel { get; set; }
        
        /// <summary>
        /// <para>M025</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("offentligTittel")]
        public string OffentligTittel { get; set; }
        
        /// <summary>
        /// <para>M021</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("beskrivelse")]
        public string Beskrivelse { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _noekkelord;
        
        /// <summary>
        /// <para>M022</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("noekkelord")]
        public System.Collections.ObjectModel.Collection<string> Noekkelord
        {
            get
            {
                return this._noekkelord;
            }
            private set
            {
                this._noekkelord = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoekkelordSpecified
        {
            get
            {
                return (this.Noekkelord.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public Mappe()
        {
            this._noekkelord = new System.Collections.ObjectModel.Collection<string>();
            this._oppbevaringssted = new System.Collections.ObjectModel.Collection<string>();
            this._part = new System.Collections.ObjectModel.Collection<Part>();
            this._kryssreferanse = new System.Collections.ObjectModel.Collection<Kryssreferanse>();
            this._merknad = new System.Collections.ObjectModel.Collection<Merknad>();
            this._klassifikasjon = new System.Collections.ObjectModel.Collection<Klassifikasjon>();
            this._mappeProperty = new System.Collections.ObjectModel.Collection<Mappe>();
            this._registrering = new System.Collections.ObjectModel.Collection<Registrering>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("dokumentmedium")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Dokumentmedium Dokumentmedium { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _oppbevaringssted;
        
        /// <summary>
        /// <para>M301</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("oppbevaringssted")]
        public System.Collections.ObjectModel.Collection<string> Oppbevaringssted
        {
            get
            {
                return this._oppbevaringssted;
            }
            private set
            {
                this._oppbevaringssted = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OppbevaringsstedSpecified
        {
            get
            {
                return (this.Oppbevaringssted.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>M600</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("opprettetDato", DataType="dateTime")]
        public System.DateTime OpprettetDatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool OpprettetDatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M600</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> OpprettetDato
        {
            get
            {
                if (this.OpprettetDatoValueSpecified)
                {
                    return this.OpprettetDatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OpprettetDatoValue = value.GetValueOrDefault();
                this.OpprettetDatoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M601</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("opprettetAv")]
        public string OpprettetAv { get; set; }
        
        /// <summary>
        /// <para>M602</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("avsluttetDato", DataType="dateTime")]
        public System.DateTime AvsluttetDatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AvsluttetDatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M602</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> AvsluttetDato
        {
            get
            {
                if (this.AvsluttetDatoValueSpecified)
                {
                    return this.AvsluttetDatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AvsluttetDatoValue = value.GetValueOrDefault();
                this.AvsluttetDatoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M603</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("avsluttetAv")]
        public string AvsluttetAv { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("arkivdel")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Kode Arkivdel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("virksomhetsspesifikkeMetadata")]
        public object VirksomhetsspesifikkeMetadata { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Part> _part;
        
        [System.Xml.Serialization.XmlElementAttribute("part")]
        public System.Collections.ObjectModel.Collection<Part> Part
        {
            get
            {
                return this._part;
            }
            private set
            {
                this._part = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartSpecified
        {
            get
            {
                return (this.Part.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Kryssreferanse> _kryssreferanse;
        
        [System.Xml.Serialization.XmlElementAttribute("kryssreferanse")]
        public System.Collections.ObjectModel.Collection<Kryssreferanse> Kryssreferanse
        {
            get
            {
                return this._kryssreferanse;
            }
            private set
            {
                this._kryssreferanse = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KryssreferanseSpecified
        {
            get
            {
                return (this.Kryssreferanse.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Merknad> _merknad;
        
        [System.Xml.Serialization.XmlElementAttribute("merknad")]
        public System.Collections.ObjectModel.Collection<Merknad> Merknad
        {
            get
            {
                return this._merknad;
            }
            private set
            {
                this._merknad = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MerknadSpecified
        {
            get
            {
                return (this.Merknad.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("skjerming")]
        public Skjerming Skjerming { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("gradering")]
        public Gradering Gradering { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Klassifikasjon> _klassifikasjon;
        
        [System.Xml.Serialization.XmlElementAttribute("klassifikasjon")]
        public System.Collections.ObjectModel.Collection<Klassifikasjon> Klassifikasjon
        {
            get
            {
                return this._klassifikasjon;
            }
            private set
            {
                this._klassifikasjon = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KlassifikasjonSpecified
        {
            get
            {
                return (this.Klassifikasjon.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("referanseEksternNoekkel")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.EksternNoekkel ReferanseEksternNoekkel { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Mappe> _mappeProperty;
        
        [System.Xml.Serialization.XmlElementAttribute("mappe")]
        public System.Collections.ObjectModel.Collection<Mappe> MappeProperty
        {
            get
            {
                return this._mappeProperty;
            }
            private set
            {
                this._mappeProperty = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MappePropertySpecified
        {
            get
            {
                return (this.MappeProperty.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Registrering> _registrering;
        
        [System.Xml.Serialization.XmlElementAttribute("registrering")]
        public System.Collections.ObjectModel.Collection<Registrering> Registrering
        {
            get
            {
                return this._registrering;
            }
            private set
            {
                this._registrering = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegistreringSpecified
        {
            get
            {
                return (this.Registrering.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("mappetype")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Kode Mappetype { get; set; }
    }
}
