//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("saksmappe", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivmelding/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("saksmappe", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivmelding/v1")]
    public partial class Saksmappe : Mappe
    {
        
        /// <summary>
        /// <para>M011</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("saksaar")]
        public int SaksaarValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SaksaarValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M011</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Saksaar
        {
            get
            {
                if (this.SaksaarValueSpecified)
                {
                    return this.SaksaarValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SaksaarValue = value.GetValueOrDefault();
                this.SaksaarValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M012</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("sakssekvensnummer")]
        public int SakssekvensnummerValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SakssekvensnummerValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M012</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Sakssekvensnummer
        {
            get
            {
                if (this.SakssekvensnummerValueSpecified)
                {
                    return this.SakssekvensnummerValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SakssekvensnummerValue = value.GetValueOrDefault();
                this.SakssekvensnummerValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M100</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("saksdato", DataType="date")]
        public System.DateTime SaksdatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SaksdatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M100</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> Saksdato
        {
            get
            {
                if (this.SaksdatoValueSpecified)
                {
                    return this.SaksdatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SaksdatoValue = value.GetValueOrDefault();
                this.SaksdatoValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("administrativEnhet")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.AdministrativEnhet AdministrativEnhet { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("saksansvarlig")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Saksansvarlig Saksansvarlig { get; set; }
        
        /// <summary>
        /// <para>M308</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("journalenhet")]
        public string Journalenhet { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("saksstatus")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Saksstatus Saksstatus { get; set; }
        
        /// <summary>
        /// <para>M106</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("utlaantDato", DataType="date")]
        public System.DateTime UtlaantDatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool UtlaantDatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M106</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> UtlaantDato
        {
            get
            {
                if (this.UtlaantDatoValueSpecified)
                {
                    return this.UtlaantDatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.UtlaantDatoValue = value.GetValueOrDefault();
                this.UtlaantDatoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M309</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("utlaantTil")]
        public string UtlaantTil { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Presedens> _presedens;
        
        [System.Xml.Serialization.XmlElementAttribute("presedens")]
        public System.Collections.ObjectModel.Collection<Presedens> Presedens
        {
            get
            {
                return this._presedens;
            }
            private set
            {
                this._presedens = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PresedensSpecified
        {
            get
            {
                return (this.Presedens.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public Saksmappe()
        {
            this._presedens = new System.Collections.ObjectModel.Collection<Presedens>();
            this._matrikkelnummer = new System.Collections.ObjectModel.Collection<Matrikkelnummer>();
            this._byggident = new System.Collections.ObjectModel.Collection<Byggident>();
            this._adresse = new System.Collections.ObjectModel.Collection<Adresse>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Matrikkelnummer> _matrikkelnummer;
        
        [System.Xml.Serialization.XmlElementAttribute("matrikkelnummer")]
        public System.Collections.ObjectModel.Collection<Matrikkelnummer> Matrikkelnummer
        {
            get
            {
                return this._matrikkelnummer;
            }
            private set
            {
                this._matrikkelnummer = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MatrikkelnummerSpecified
        {
            get
            {
                return (this.Matrikkelnummer.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Byggident> _byggident;
        
        [System.Xml.Serialization.XmlElementAttribute("byggident")]
        public System.Collections.ObjectModel.Collection<Byggident> Byggident
        {
            get
            {
                return this._byggident;
            }
            private set
            {
                this._byggident = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ByggidentSpecified
        {
            get
            {
                return (this.Byggident.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("planident")]
        public Planident Planident { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("punkt")]
        public Punkt Punkt { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Adresse> _adresse;
        
        [System.Xml.Serialization.XmlElementAttribute("adresse")]
        public System.Collections.ObjectModel.Collection<Adresse> Adresse
        {
            get
            {
                return this._adresse;
            }
            private set
            {
                this._adresse = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdresseSpecified
        {
            get
            {
                return (this.Adresse.Count != 0);
            }
        }
    }
}
