//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Innsyn.Sok
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("dokumentbeskrivelseSokefelt", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/sok/v1")]
    public enum DokumentbeskrivelseSokefelt
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelseEksternId")]
        DokumentbeskrivelseEksternId,
        
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelseOpprettetDato")]
        DokumentbeskrivelseOpprettetDato,
        
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelseTittel")]
        DokumentbeskrivelseTittel,
        
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelseDokumenttype")]
        DokumentbeskrivelseDokumenttype,
        
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelseDokumentstatus")]
        DokumentbeskrivelseDokumentstatus,
        
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelseSkjermingTilgangsrestriksjon")]
        DokumentbeskrivelseSkjermingTilgangsrestriksjon,
        
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelseSkjermingSkjermingshjemmel")]
        DokumentbeskrivelseSkjermingSkjermingshjemmel,
        
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelseSkjermingSkjermingsvarighet")]
        DokumentbeskrivelseSkjermingSkjermingsvarighet,
        
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelseSkjermingSkjermingOpphoererDato")]
        DokumentbeskrivelseSkjermingSkjermingOpphoererDato,
    }
}
