//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Innsyn.Sok
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("journalpostSokefelt", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/sok/v1")]
    public enum JournalpostSokefelt
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringEksternId")]
        RegistreringEksternId,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringOpprettetDato")]
        RegistreringOpprettetDato,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringTittel")]
        RegistreringTittel,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringAdministrativenhet")]
        RegistreringAdministrativenhet,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringJournalpostansvarlig")]
        RegistreringJournalpostansvarlig,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringEndretFoerDato")]
        RegistreringEndretFoerDato,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringEndretEtterDato")]
        RegistreringEndretEtterDato,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringPartPartNavn")]
        RegistreringPartPartNavn,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringPartPartRolle")]
        RegistreringPartPartRolle,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringPartPostadresse")]
        RegistreringPartPostadresse,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringPartPostnummer")]
        RegistreringPartPostnummer,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringPartPoststed")]
        RegistreringPartPoststed,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringPartEpostadresse")]
        RegistreringPartEpostadresse,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringSkjermingTilgangsrestriksjon")]
        RegistreringSkjermingTilgangsrestriksjon,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringSkjermingSkjermingshjemmel")]
        RegistreringSkjermingSkjermingshjemmel,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringSkjermingSkjermingsvarighet")]
        RegistreringSkjermingSkjermingsvarighet,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringSkjermingSkjermingOpphoererDato")]
        RegistreringSkjermingSkjermingOpphoererDato,
        
        [System.Xml.Serialization.XmlEnumAttribute("journalpostJournalaar")]
        JournalpostJournalaar,
        
        [System.Xml.Serialization.XmlEnumAttribute("journalpostJournalsekvensnummer")]
        JournalpostJournalsekvensnummer,
        
        [System.Xml.Serialization.XmlEnumAttribute("journalpostSaksaar")]
        JournalpostSaksaar,
        
        [System.Xml.Serialization.XmlEnumAttribute("journalpostSakssekvensnummer")]
        JournalpostSakssekvensnummer,
        
        [System.Xml.Serialization.XmlEnumAttribute("journalpostJournalpostnummer")]
        JournalpostJournalpostnummer,
        
        [System.Xml.Serialization.XmlEnumAttribute("journalpostJournalposttype")]
        JournalpostJournalposttype,
        
        [System.Xml.Serialization.XmlEnumAttribute("journalpostJournalstatus")]
        JournalpostJournalstatus,
        
        [System.Xml.Serialization.XmlEnumAttribute("journalpostJournaldato")]
        JournalpostJournaldato,
        
        [System.Xml.Serialization.XmlEnumAttribute("journalpostDokumentetsdato")]
        JournalpostDokumentetsdato,
        
        [System.Xml.Serialization.XmlEnumAttribute("journalpostForfallsdato")]
        JournalpostForfallsdato,
    }
}
