//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Innsyn.Sok
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("parameter", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/sok/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DokumentbeskrivelseParameter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JournalpostParameter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MappeParameter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistreringParameter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SaksmappeParameter))]
    public abstract partial class Parameter
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("operator")]
        public OperatorType Operator { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("sokVerdier")]
        public SokVerdier SokVerdier { get; set; }
    }
}
