//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Innsyn.Sok
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("registreringSokefelt", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/sok/v1")]
    public enum RegistreringSokefelt
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringEksternId")]
        RegistreringEksternId,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringOpprettetDato")]
        RegistreringOpprettetDato,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringTittel")]
        RegistreringTittel,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringAdministrativenhet")]
        RegistreringAdministrativenhet,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringJournalpostansvarlig")]
        RegistreringJournalpostansvarlig,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringEndretFoerDato")]
        RegistreringEndretFoerDato,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringEndretEtterDato")]
        RegistreringEndretEtterDato,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringPartPartNavn")]
        RegistreringPartPartNavn,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringPartPartRolle")]
        RegistreringPartPartRolle,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringPartPostadresse")]
        RegistreringPartPostadresse,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringPartPostnummer")]
        RegistreringPartPostnummer,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringPartPoststed")]
        RegistreringPartPoststed,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringPartEpostadresse")]
        RegistreringPartEpostadresse,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringSkjermingTilgangsrestriksjon")]
        RegistreringSkjermingTilgangsrestriksjon,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringSkjermingSkjermingshjemmel")]
        RegistreringSkjermingSkjermingshjemmel,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringSkjermingSkjermingsvarighet")]
        RegistreringSkjermingSkjermingsvarighet,
        
        [System.Xml.Serialization.XmlEnumAttribute("registreringSkjermingSkjermingOpphoererDato")]
        RegistreringSkjermingSkjermingOpphoererDato,
    }
}
