//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Innsyn.Sok
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("resultatType", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/sokeresultat/v1")]
    public enum ResultatType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("mappe")]
        Mappe,
        
        [System.Xml.Serialization.XmlEnumAttribute("saksmappe")]
        Saksmappe,
        
        [System.Xml.Serialization.XmlEnumAttribute("registrering")]
        Registrering,
        
        [System.Xml.Serialization.XmlEnumAttribute("journalpost")]
        Journalpost,
        
        [System.Xml.Serialization.XmlEnumAttribute("journalpostMedSaksmappe")]
        JournalpostMedSaksmappe,
        
        [System.Xml.Serialization.XmlEnumAttribute("dokumentbeskrivelse")]
        Dokumentbeskrivelse,
    }
}
