//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Innsyn.Sok
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("resultat", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/sokeresultat/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Resultat
    {
        
        [System.Xml.Serialization.XmlElementAttribute("mappe")]
        public KS.Fiks.Arkiv.Models.V1.Arkivstruktur.Mappe Mappe { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("saksmappe")]
        public KS.Fiks.Arkiv.Models.V1.Arkivstruktur.Saksmappe Saksmappe { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("registrering")]
        public KS.Fiks.Arkiv.Models.V1.Arkivstruktur.Registrering Registrering { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("journalpost")]
        public KS.Fiks.Arkiv.Models.V1.Arkivstruktur.Journalpost Journalpost { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("journalpostMedSaksmappe")]
        public KS.Fiks.Arkiv.Models.V1.Arkivstruktur.JournalpostMedSaksmappe JournalpostMedSaksmappe { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("dokumentbeskrivelse")]
        public KS.Fiks.Arkiv.Models.V1.Arkivstruktur.Dokumentbeskrivelse Dokumentbeskrivelse { get; set; }
    }
}
