//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Innsyn.Sok
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("resultatListe", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/sokeresultat/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResultatListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Resultat> _resultat;
        
        [System.Xml.Serialization.XmlElementAttribute("resultat")]
        public System.Collections.ObjectModel.Collection<Resultat> Resultat
        {
            get
            {
                return this._resultat;
            }
            private set
            {
                this._resultat = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResultatSpecified
        {
            get
            {
                return (this.Resultat.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public ResultatListe()
        {
            this._resultat = new System.Collections.ObjectModel.Collection<Resultat>();
        }
    }
}
