//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Innsyn.Sok
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("saksmappeSokefelt", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/sok/v1")]
    public enum SaksmappeSokefelt
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeEksternId")]
        MappeEksternId,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeTittel")]
        MappeTittel,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeOpprettetDato")]
        MappeOpprettetDato,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeBeskrivelse")]
        MappeBeskrivelse,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeNoekkelord")]
        MappeNoekkelord,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeAvsluttetDato")]
        MappeAvsluttetDato,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeArkivdel")]
        MappeArkivdel,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeEndretFoerDato")]
        MappeEndretFoerDato,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeEndretEtterDato")]
        MappeEndretEtterDato,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeMappetype")]
        MappeMappetype,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeKlasseKlassifikasjonssystem")]
        MappeKlasseKlassifikasjonssystem,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeKlasseKlasseID")]
        MappeKlasseKlasseID,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeKlasseTittel")]
        MappeKlasseTittel,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeKlasseBeskrivelse")]
        MappeKlasseBeskrivelse,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappePartPartNavn")]
        MappePartPartNavn,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappePartPartRolle")]
        MappePartPartRolle,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappePartPostadresse")]
        MappePartPostadresse,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappePartPostnummer")]
        MappePartPostnummer,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappePartPoststed")]
        MappePartPoststed,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappePartEpostadresse")]
        MappePartEpostadresse,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeSkjermingTilgangsrestriksjon")]
        MappeSkjermingTilgangsrestriksjon,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeSkjermingSkjermingshjemmel")]
        MappeSkjermingSkjermingshjemmel,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeSkjermingSkjermingsvarighet")]
        MappeSkjermingSkjermingsvarighet,
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeSkjermingSkjermingOpphoererDato")]
        MappeSkjermingSkjermingOpphoererDato,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakSaksdato")]
        SakSaksdato,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakSaksaar")]
        SakSaksaar,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakSaksekvensnummer")]
        SakSaksekvensnummer,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakSaksstatus")]
        SakSaksstatus,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakAdministrativenhet")]
        SakAdministrativenhet,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakSaksansvarlig")]
        SakSaksansvarlig,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakMatrikkelnummerKommunenummer")]
        SakMatrikkelnummerKommunenummer,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakMatrikkelnummerGaardsnummer")]
        SakMatrikkelnummerGaardsnummer,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakMatrikkelnummerBruksnummer")]
        SakMatrikkelnummerBruksnummer,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakMatrikkelnummerFestenummer")]
        SakMatrikkelnummerFestenummer,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakMatrikkelnummerSeksjonsnummer")]
        SakMatrikkelnummerSeksjonsnummer,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakByggidentBygningsnummer")]
        SakByggidentBygningsnummer,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakByggidentEndringsloepenummer")]
        SakByggidentEndringsloepenummer,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakPlanidentStatLandkode")]
        SakPlanidentStatLandkode,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakPlanidentFylkeFylkesnummer")]
        SakPlanidentFylkeFylkesnummer,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakPlanidentKommuneKommunenummer")]
        SakPlanidentKommuneKommunenummer,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakPlanidentPlanidentifikasjon")]
        SakPlanidentPlanidentifikasjon,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakPartOrganisasjonsid")]
        SakPartOrganisasjonsid,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakPartPersonid")]
        SakPartPersonid,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakBbox")]
        SakBbox,
    }
}
