//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Innsyn.Sok
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("saksmappeSorteringsfelt", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/sok/v1")]
    public enum SaksmappeSorteringsfelt
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("mappeOpprettetDato")]
        MappeOpprettetDato,
        
        [System.Xml.Serialization.XmlEnumAttribute("sakSaksaar-saksekvensnummer")]
        SakSaksaar_Saksekvensnummer,
    }
}
