//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Innsyn.Hent.Mappe
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("inkluder", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/mappe/hent/v1")]
    [System.Xml.Serialization.XmlRootAttribute("inkluder", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/mappe/hent/v1")]
    public enum Inkluder
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("merknad")]
        Merknad,
        
        [System.Xml.Serialization.XmlEnumAttribute("noekkelord")]
        Noekkelord,
        
        [System.Xml.Serialization.XmlEnumAttribute("kryssreferanse")]
        Kryssreferanse,
        
        [System.Xml.Serialization.XmlEnumAttribute("klasse")]
        Klasse,
        
        [System.Xml.Serialization.XmlEnumAttribute("part")]
        Part,
        
        [System.Xml.Serialization.XmlEnumAttribute("presedens")]
        Presedens,
        
        [System.Xml.Serialization.XmlEnumAttribute("moetedeltaker")]
        Moetedeltaker,
    }
}
