//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Innsyn.Hent.Mappe
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("mappeHentResultat", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/mappe/hent/resultat/" +
        "v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("mappeHentResultat", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/mappe/hent/resultat/" +
        "v1")]
    public partial class MappeHentResultat
    {
        
        [System.Xml.Serialization.XmlElementAttribute("mappe")]
        public KS.Fiks.Arkiv.Models.V1.Arkivstruktur.Mappe Mappe { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("saksmappe")]
        public KS.Fiks.Arkiv.Models.V1.Arkivstruktur.Saksmappe Saksmappe { get; set; }
    }
}
