//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Innsyn.Hent.Registrering
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("registreringHentResultat", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/registrering/hent/re" +
        "sultat/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("registreringHentResultat", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/registrering/hent/re" +
        "sultat/v1")]
    public partial class RegistreringHentResultat
    {
        
        [System.Xml.Serialization.XmlElementAttribute("registrering")]
        public KS.Fiks.Arkiv.Models.V1.Arkivstruktur.Registrering Registrering { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("journalpost")]
        public KS.Fiks.Arkiv.Models.V1.Arkivstruktur.Journalpost Journalpost { get; set; }
    }
}
