//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmeldingkvittering
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("journalpostKvittering", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivmeldingkvitteri" +
        "ng/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JournalpostKvittering : RegistreringKvittering
    {
        
        /// <summary>
        /// <para>M013</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("journalaar")]
        public int Journalaar { get; set; }
        
        /// <summary>
        /// <para>M014</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("journalsekvensnummer")]
        public int Journalsekvensnummer { get; set; }
        
        /// <summary>
        /// <para>M015</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("journalpostnummer")]
        public int Journalpostnummer { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("journalposttype")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Journalposttype Journalposttype { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("journalstatus")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Journalstatus Journalstatus { get; set; }
        
        /// <summary>
        /// <para>M101</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("journaldato", DataType="date")]
        public System.DateTime Journaldato { get; set; }
        
        /// <summary>
        /// <para>M109</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("forfallsdato", DataType="date")]
        public System.DateTime ForfallsdatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ForfallsdatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M109</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> Forfallsdato
        {
            get
            {
                if (this.ForfallsdatoValueSpecified)
                {
                    return this.ForfallsdatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ForfallsdatoValue = value.GetValueOrDefault();
                this.ForfallsdatoValueSpecified = value.HasValue;
            }
        }
    }
}
