//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmeldingkvittering
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("registreringKvittering", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivmeldingkvitteri" +
        "ng/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JournalpostKvittering))]
    public partial class RegistreringKvittering
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("systemID")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.SystemID SystemID { get; set; }
        
        /// <summary>
        /// <para>M600</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("opprettetDato", DataType="dateTime")]
        public System.DateTime OpprettetDatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool OpprettetDatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M600</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> OpprettetDato
        {
            get
            {
                if (this.OpprettetDatoValueSpecified)
                {
                    return this.OpprettetDatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OpprettetDatoValue = value.GetValueOrDefault();
                this.OpprettetDatoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M601</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("opprettetAv")]
        public string OpprettetAv { get; set; }
        
        /// <summary>
        /// <para>M604</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("arkivertDato", DataType="dateTime")]
        public System.DateTime ArkivertDatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ArkivertDatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M604</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> ArkivertDato
        {
            get
            {
                if (this.ArkivertDatoValueSpecified)
                {
                    return this.ArkivertDatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ArkivertDatoValue = value.GetValueOrDefault();
                this.ArkivertDatoValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M605</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("arkivertAv")]
        public string ArkivertAv { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DokumentbeskrivelseKvittering> _dokumentbeskrivelseKvittering;
        
        [System.Xml.Serialization.XmlElementAttribute("dokumentbeskrivelseKvittering")]
        public System.Collections.ObjectModel.Collection<DokumentbeskrivelseKvittering> DokumentbeskrivelseKvittering
        {
            get
            {
                return this._dokumentbeskrivelseKvittering;
            }
            private set
            {
                this._dokumentbeskrivelseKvittering = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DokumentbeskrivelseKvitteringSpecified
        {
            get
            {
                return (this.DokumentbeskrivelseKvittering.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public RegistreringKvittering()
        {
            this._dokumentbeskrivelseKvittering = new System.Collections.ObjectModel.Collection<DokumentbeskrivelseKvittering>();
        }
        
        /// <summary>
        /// <para>M004</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("registreringsID")]
        public string RegistreringsID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("referanseEksternNoekkel")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.EksternNoekkel ReferanseEksternNoekkel { get; set; }
    }
}
