//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmeldingkvittering
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("saksmappeKvittering", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivmeldingkvitteri" +
        "ng/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaksmappeKvittering : MappeKvittering
    {
        
        /// <summary>
        /// <para>M011</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("saksaar")]
        public int SaksaarValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SaksaarValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M011</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Saksaar
        {
            get
            {
                if (this.SaksaarValueSpecified)
                {
                    return this.SaksaarValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SaksaarValue = value.GetValueOrDefault();
                this.SaksaarValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M012</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("sakssekvensnummer")]
        public int SakssekvensnummerValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SakssekvensnummerValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M012</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Sakssekvensnummer
        {
            get
            {
                if (this.SakssekvensnummerValueSpecified)
                {
                    return this.SakssekvensnummerValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SakssekvensnummerValue = value.GetValueOrDefault();
                this.SakssekvensnummerValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M100</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("saksdato", DataType="date")]
        public System.DateTime SaksdatoValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SaksdatoValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M100</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> Saksdato
        {
            get
            {
                if (this.SaksdatoValueSpecified)
                {
                    return this.SaksdatoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SaksdatoValue = value.GetValueOrDefault();
                this.SaksdatoValueSpecified = value.HasValue;
            }
        }
    }
}
