//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding.Oppdatering
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("arkivmeldingOppdatering", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivmeldingoppdater" +
        "ing/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("arkivmeldingOppdatering", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivmeldingoppdater" +
        "ing/v1")]
    public partial class ArkivmeldingOppdatering
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("meldingId")]
        public string MeldingId { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("tidspunkt", DataType="dateTime")]
        public System.DateTime Tidspunkt { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MappeOppdatering> _mappeOppdateringer;
        
        [System.Xml.Serialization.XmlElementAttribute("mappeOppdateringer")]
        public System.Collections.ObjectModel.Collection<MappeOppdatering> MappeOppdateringer
        {
            get
            {
                return this._mappeOppdateringer;
            }
            private set
            {
                this._mappeOppdateringer = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MappeOppdateringerSpecified
        {
            get
            {
                return (this.MappeOppdateringer.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public ArkivmeldingOppdatering()
        {
            this._mappeOppdateringer = new System.Collections.ObjectModel.Collection<MappeOppdatering>();
            this._registreringOppdateringer = new System.Collections.ObjectModel.Collection<RegistreringOppdatering>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RegistreringOppdatering> _registreringOppdateringer;
        
        [System.Xml.Serialization.XmlElementAttribute("registreringOppdateringer")]
        public System.Collections.ObjectModel.Collection<RegistreringOppdatering> RegistreringOppdateringer
        {
            get
            {
                return this._registreringOppdateringer;
            }
            private set
            {
                this._registreringOppdateringer = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegistreringOppdateringerSpecified
        {
            get
            {
                return (this.RegistreringOppdateringer.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("dokumentbeskrivelseOppdatering")]
        public DokumentbeskrivelseOppdatering DokumentbeskrivelseOppdatering { get; set; }
    }
}
