//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding.Oppdatering
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("korrespondansepartOppdateringer", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivmeldingoppdater" +
        "ing/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KorrespondansepartOppdateringer
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<KorrespondansepartOppdatering> _oppdatering;
        
        [System.Xml.Serialization.XmlElementAttribute("oppdatering")]
        public System.Collections.ObjectModel.Collection<KorrespondansepartOppdatering> Oppdatering
        {
            get
            {
                return this._oppdatering;
            }
            private set
            {
                this._oppdatering = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OppdateringSpecified
        {
            get
            {
                return (this.Oppdatering.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public KorrespondansepartOppdateringer()
        {
            this._oppdatering = new System.Collections.ObjectModel.Collection<KorrespondansepartOppdatering>();
            this._slett = new System.Collections.ObjectModel.Collection<KorrespondansepartSlett>();
            this._ny = new System.Collections.ObjectModel.Collection<KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding.Korrespondansepart>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<KorrespondansepartSlett> _slett;
        
        [System.Xml.Serialization.XmlElementAttribute("slett")]
        public System.Collections.ObjectModel.Collection<KorrespondansepartSlett> Slett
        {
            get
            {
                return this._slett;
            }
            private set
            {
                this._slett = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SlettSpecified
        {
            get
            {
                return (this.Slett.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding.Korrespondansepart> _ny;
        
        [System.Xml.Serialization.XmlElementAttribute("ny")]
        public System.Collections.ObjectModel.Collection<KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding.Korrespondansepart> Ny
        {
            get
            {
                return this._ny;
            }
            private set
            {
                this._ny = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NySpecified
        {
            get
            {
                return (this.Ny.Count != 0);
            }
        }
    }
}
