//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding.Oppdatering
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("registreringOppdatering", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivmeldingoppdater" +
        "ing/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JournalpostOppdatering))]
    public partial class RegistreringOppdatering
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("referanseTilRegistrering")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.ReferanseTilRegistrering ReferanseTilRegistrering { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("referanseEksternNoekkel")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.EksternNoekkel ReferanseEksternNoekkel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("partOppdateringer")]
        public PartOppdateringer PartOppdateringer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("skjerming")]
        public KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding.Skjerming Skjerming { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("gradering")]
        public KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding.Gradering Gradering { get; set; }
        
        /// <summary>
        /// <para>M020</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("tittel")]
        public string Tittel { get; set; }
        
        /// <summary>
        /// <para>M025</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("offentligTittel")]
        public string OffentligTittel { get; set; }
        
        /// <summary>
        /// <para>M021</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("beskrivelse")]
        public string Beskrivelse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("virksomhetsspesifikkeMetadata")]
        public object VirksomhetsspesifikkeMetadata { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("merknadOppdateringer")]
        public MerknadOppdateringer MerknadOppdateringer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("korrespondansepartOppdateringer")]
        public KorrespondansepartOppdateringer KorrespondansepartOppdateringer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("klassifikasjonOppdateringer")]
        public KlassifikasjonOppdateringer KlassifikasjonOppdateringer { get; set; }
    }
}
