//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding.Oppdatering
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("saksmappeOppdatering", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivmeldingoppdater" +
        "ing/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaksmappeOppdatering : MappeOppdatering
    {
        
        [System.Xml.Serialization.XmlElementAttribute("administrativEnhet")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.AdministrativEnhet AdministrativEnhet { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("saksansvarlig")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Saksansvarlig Saksansvarlig { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("saksstatus")]
        public KS.Fiks.Arkiv.Models.V1.Metadatakatalog.Saksstatus Saksstatus { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("matrikkelnummerOppdateringer")]
        public MatrikkelnummerOppdateringer MatrikkelnummerOppdateringer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("byggidentOppdateringer")]
        public ByggidentOppdateringer ByggidentOppdateringer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("planidentOppdateringer")]
        public PlanidentOppdateringer PlanidentOppdateringer { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding.Punkt> _punkt;
        
        [System.Xml.Serialization.XmlElementAttribute("punkt")]
        public System.Collections.ObjectModel.Collection<KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding.Punkt> Punkt
        {
            get
            {
                return this._punkt;
            }
            private set
            {
                this._punkt = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PunktSpecified
        {
            get
            {
                return (this.Punkt.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public SaksmappeOppdatering()
        {
            this._punkt = new System.Collections.ObjectModel.Collection<KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding.Punkt>();
        }
    }
}
