//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.662.0
namespace KS.Fiks.Arkiv.Models.V1.Arkivstruktur.Noekler
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.662.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("journalpostNoekler", Namespace="https://ks-no.github.io/standarder/fiks-protokoll/fiks-arkiv/arkivstruktur/noekle" +
        "r/v1")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JournalpostNoekler : RegistreringNoekler
    {
        
        /// <summary>
        /// <para>M013</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("journalaar")]
        public int JournalaarValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool JournalaarValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M013</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Journalaar
        {
            get
            {
                if (this.JournalaarValueSpecified)
                {
                    return this.JournalaarValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.JournalaarValue = value.GetValueOrDefault();
                this.JournalaarValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M014</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("journalsekvensnummer")]
        public int JournalsekvensnummerValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool JournalsekvensnummerValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M014</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Journalsekvensnummer
        {
            get
            {
                if (this.JournalsekvensnummerValueSpecified)
                {
                    return this.JournalsekvensnummerValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.JournalsekvensnummerValue = value.GetValueOrDefault();
                this.JournalsekvensnummerValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>M015</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("journalpostnummer")]
        public int JournalpostnummerValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool JournalpostnummerValueSpecified { get; set; }
        
        /// <summary>
        /// <para>M015</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Journalpostnummer
        {
            get
            {
                if (this.JournalpostnummerValueSpecified)
                {
                    return this.JournalpostnummerValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.JournalpostnummerValue = value.GetValueOrDefault();
                this.JournalpostnummerValueSpecified = value.HasValue;
            }
        }
    }
}
